services:
  # Servicio 1: Base de Datos SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - inventory_network
    volumes:
      - mssql_data:/var/opt/mssql

  # Servicio 2: Tu Web API .NET
  api:
    image: apitest-api
    container_name: apitest_api_container
    build:
      context: .
      dockerfile: src/ApiTest.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ApiTestDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - JwtSettings__Secret=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - inventory_network

networks:
  inventory_network:
    driver: bridge

volumes:
  mssql_data: