


# OBTIENE LA LISTA DE PRODUCTOS
GET http://localhost:8080/api/products


### OBTIENE UN PRODUCTO ESPECIFICO

http://localhost:8080/api/products/2

### INSERTA UN NUEVO PRODUCTO
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Teclado iluminado Series X",
  "description": "Teclado profesional gammer",
  "price": 149.99,
  "stock": 10,
  "categoryId": 1
}

### ACTUALIZA EL STOCK

POST http://localhost:8080/api/products/movements
Content-Type: application/json

{
    "productId": 2,
    "quantity": 100,
    "movementType": "Output",
    "reason": "Venta al cliente final"
}

### ELIMINA DE FORMA LOGICA UN PRODUCTO

DELETE http://localhost:8080/api/products/1

### REACTIVA EL PRODUCTO

PATCH http://localhost:8080/api/products/1/reactivate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW5Vc2VyIiwiZXhwIjoxNzg0MzI1MDgxLCJpc3MiOiJBcGlUZXN0IiwiYXVkIjoiQXBpVGVzdFVzZXJzIn0.PyxkD9jeFxe6_1rN6lHYNIMihvKy_CMo-U2IWQ7Dkxo

### REACTIVA CATEGORIA

PATCH http://localhost:8080/api/categories/1/reactivate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW5Vc2VyIiwiZXhwIjoxNzg0MzI5MTU4LCJpc3MiOiJBcGlUZXN0IiwiYXVkIjoiQXBpVGVzdFVzZXJzIn0.HKQII77jv2w87bC6wecV1L3X-3Y5d6YiRXE3ROmLJRs

### Actualizar descripción y precio de un producto
PUT http://localhost:8080/api/products/2
Content-Type: application/json

{
    "productId": 2,
    "name": "Teclado iluminado mecánico",
    "description": "Teclado profesional con switches rojos",
    "price": 159.99
}

### Actualizar nombre y descripción de una categoría
PUT http://localhost:8080/api/categories/1
Content-Type: application/json


{
    "categoryId": 1,
    "name": "Electrónica avanzada",
    "description": "Dispositivos de alta gama y componentes"
}

### Obtener todas las categorías activas
GET http://localhost:8080/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW5Vc2VyIiwiZXhwIjoxNzg0MzI1MDgxLCJpc3MiOiJBcGlUZXN0IiwiYXVkIjoiQXBpVGVzdFVzZXJzIn0.PyxkD9jeFxe6_1rN6lHYNIMihvKy_CMo-U2IWQ7Dkxo

### Obtener una categoría específica
GET http://localhost:8080/api/categories/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW5Vc2VyIiwiZXhwIjoxNzg0MzI1MDgxLCJpc3MiOiJBcGlUZXN0IiwiYXVkIjoiQXBpVGVzdFVzZXJzIn0.PyxkD9jeFxe6_1rN6lHYNIMihvKy_CMo-U2IWQ7Dkxo

### Crear nueva categoría
POST http://localhost:8080/api/categories
Content-Type: application/json

{
    "name": "Farmacia",
    "description": "Artículos cuidado personal"
}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW5Vc2VyIiwiZXhwIjoxNzg0MzI3OTY1LCJpc3MiOiJBcGlUZXN0IiwiYXVkIjoiQXBpVGVzdFVzZXJzIn0.0ypgG5NB1YylerlCPQzWIfs5vAgiGe6LPPy2Vg14R6E

### Actualizar categoría existente
PUT http://localhost:8080/api/categories/1
Content-Type: application/json

{
    "categoryId": 1,
    "name": "Electrónica Actualizada",
    "description": "Nueva descripción"
}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW5Vc2VyIiwiZXhwIjoxNzg0MzI3OTY1LCJpc3MiOiJBcGlUZXN0IiwiYXVkIjoiQXBpVGVzdFVzZXJzIn0.0ypgG5NB1YylerlCPQzWIfs5vAgiGe6LPPy2Vg14R6E

### Borrado lógico de una categoría
DELETE http://localhost:8080/api/categories/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW5Vc2VyIiwiZXhwIjoxNzg0MzI5MTU4LCJpc3MiOiJBcGlUZXN0IiwiYXVkIjoiQXBpVGVzdFVzZXJzIn0.HKQII77jv2w87bC6wecV1L3X-3Y5d6YiRXE3ROmLJRs

### Generar Token de Prueba
POST http://localhost:8080/api/auth/login
Content-Type: application/json

